import { describe, expect, it } from "vitest";
import { noUngroundedSummary } from "./resume.js";

/**
 * Grounding the summary sentence (AGENT.md open question 11).
 *
 * `groundSkills` filtered the skills array and `noInventedExperience` caught
 * claims of employment; nothing read the summary for a claim of *knowledge*.
 * Five evaluation runs produced the same failure every time, on **both** model
 * sizes, which is why the fix is here and not a bigger model.
 *
 * The sentences marked "from a real run" were generated by qwen3.5 and stored
 * in a resume. They are the specification for this guard.
 */

/** What the seeded catalogue teaches, which is what the guard checks against. */
const VOCABULARY = ["HTML", "CSS", "JavaScript", "Git", "React", "Vue", "HTTP and servers"];

const skill = (name: string) => ({ name });

describe("a learner with nothing verified", () => {
  const verified: { name: string }[] = [];

  /** From a real run, qwen3.5:4b. The resume printed no skills above this. */
  it("rejects “foundational knowledge of web technologies”", () => {
    const reason = noUngroundedSummary(
      {
        summary:
          "Aspiring front-end developer with foundational knowledge of web technologies and a " +
          "commitment to continuous learning. Ready to apply core programming concepts to build " +
          "responsive user interfaces.",
      },
      verified,
      VOCABULARY,
    );
    expect(reason).not.toBeNull();
  });

  /** From a real run, qwen3.5:9b — the same failure a model twice the size made. */
  it("rejects the 9b wording too", () => {
    const reason = noUngroundedSummary(
      { summary: "Aspiring front-end developer with foundational knowledge of web technologies." },
      verified,
      VOCABULARY,
    );
    expect(reason).not.toBeNull();
  });

  it.each([
    "Familiar with HTML and CSS from completed coursework.",
    "Proficient in JavaScript fundamentals.",
    "Developer with a solid understanding of web development principles.",
    "Strong grasp of programming concepts.",
  ])("rejects %s", (summary) => {
    expect(noUngroundedSummary({ summary }, verified, VOCABULARY)).not.toBeNull();
  });

  /**
   * What the prompt now asks for instead. These must pass, or the guard would
   * reject every possible answer and the job would fail after three retries —
   * leaving the learner worse off than the wrong sentence did.
   */
  it.each([
    "Aspiring front-end developer working toward a first role in web development.",
    "Learning to program, with the goal of becoming a junior web developer.",
    "Working toward a career as a back-end developer.",
  ])("allows %s", (summary) => {
    expect(noUngroundedSummary({ summary }, verified, VOCABULARY)).toBeNull();
  });
});

describe("a learner with some evidence", () => {
  const verified = [skill("HTML"), skill("CSS")];

  /**
   * The rule is *ungrounded* claims, not claims. With real evidence this is
   * exactly what a summary should say, and a guard that rejected it would push
   * the model toward saying nothing useful.
   */
  it("allows a claim about what was actually proven", () => {
    const summary = "Foundational knowledge of HTML and CSS, demonstrated through completed modules.";
    expect(noUngroundedSummary({ summary }, verified, VOCABULARY)).toBeNull();
  });

  /** The partial-evidence case: two skills proven, a third claimed. */
  it("rejects a skill the learner has not proven", () => {
    const reason = noUngroundedSummary(
      { summary: "Foundational knowledge of HTML, CSS and JavaScript." },
      verified,
      VOCABULARY,
    );
    expect(reason).not.toBeNull();
    expect(reason).toContain("JavaScript");
    // The retry is told what it may say, not only what it may not.
    expect(reason).toContain("HTML");
  });

  it("rejects a framework reached for from the catalogue", () => {
    const reason = noUngroundedSummary(
      { summary: "Front-end developer with HTML, CSS and React experience." },
      verified,
      VOCABULARY,
    );
    expect(reason).toContain("React");
  });

  /** A term the platform does not teach is out of scope, and says so honestly. */
  it("does not check a skill the platform has no name for", () => {
    const summary = "Foundational knowledge of HTML and CSS, plus Photoshop.";
    expect(noUngroundedSummary({ summary }, verified, VOCABULARY)).toBeNull();
  });
});

describe("matching a name", () => {
  const verified = [skill("HTML")];

  /** "CSS" inside "CSS-in-JS" is still CSS; a substring of a word is not. */
  it("does not fire on a name inside a longer word", () => {
    expect(
      noUngroundedSummary({ summary: "Knowledge of HTML and cascading styles." }, verified, ["CSS"]),
    ).toBeNull();
  });

  it("is case-insensitive", () => {
    const reason = noUngroundedSummary({ summary: "Knowledge of html and javascript." }, verified, [
      "JavaScript",
    ]);
    expect(reason).not.toBeNull();
  });

  /** Names with punctuation must not blow up the expression that looks for them. */
  it.each(["C++", "Node.js", "F#"])("handles %s without breaking the regex", (name) => {
    expect(() =>
      noUngroundedSummary({ summary: `Knowledge of ${name}.` }, verified, [name]),
    ).not.toThrow();
    expect(noUngroundedSummary({ summary: `Knowledge of ${name}.` }, verified, [name])).not.toBeNull();
  });
});
